application: helloworld
# helloworld application
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.app

libraries:
- name: jinja2
  version: latest

env_variables:
  TMP: \Users\Leah\Desktop\output.txt